version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    container_name: pg01
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    container_name: re01
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
    image: perylemke/railsapi:local
    entrypoint: ./entrypoint.sh
    container_name: rs01
    links:
      - postgres:postgres
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/rails_api'
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
